travis:
  secure:
    BINSTAR_TOKEN: hqBfKr1Ln8x2p8ed17KOGzJqnVVYwKPtE8DeunDPnf0L+c0J+nQlHmiUPCA6m1LPUmemiNFm/3VKaCjoFW6KC61mfwjtr1aEiMIg5Nv6Bw3oBnqd/Xae5yQKgjAyvNH/JpihIOdJhUaXmx2rx6wsiIHGXfW2Hu76BzXJlm1O+VV0TKEXb94h3j+mQnDZYAkLPupIjrwDNjBWcwd06plKAndiV3VTu6FZNE+FuraDc6VTF7BHMVsTWbkPMVVOCHOx04m7tyN7oji7zee6zUyMZYr8j6EpNTA0gfKD01DuIgt71rLroOdheByzsabVttroxPthGeMDyFSrYnvIuJObEOPdlDijFyM9DrYSYT5375f8uCGkkahmOXG7i6oaVSBBxA2dAPuSRJHWbZL/D8tdlzhYNSBCGb0nC8EXCQpRWQaqpjrkrgvHOxKQ4ueW2uTX4Zrw2/kI3EJ6TeKGK99FCiFpTMnc74RoDYVaDWqn1xMEr1SjgDaOHVF7b2C6lq9LHffxnEdbrBFDXRDUbeEmSdpsTpSKKDT8H0o2QamlX9CdDnnChwT+APqWrqCe0unfKlGkqv4piCjF/a5lQ3UrpKbaMEFgioI7d4icKw1URejEcsv3siJrKGmgom7VO/dygAVki0W0nGr5/ajs0HEucUJaPgzOdMr4XXRlnt4mBTM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
